mydata <- read.table("household_power_consumption.txt", skip = 1, sep = ";")
names(mydata) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
submydata <- subset(mydata, mydata$Date=="1/2/2007" | mydata$Date=="2/2/2007")
date_time <- strptime(paste(submydata$Date,submydata$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
GlobalActivePower2 <- as.numeric(submydata$Global_active_power)
plot(date_time, GlobalActivePower2, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
png("plot2.png", width = 480, height = 480)
plot(date_time, GlobalActivePower2, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()
