mydata <- read.table("household_power_consumption.txt", skip = 1, sep = ";")
names(mydata) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
submydata <- subset(mydata, mydata$Date=="1/2/2007" | mydata$Date=="2/2/2007")
date_time <- strptime(paste(submydata$Date,submydata$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
GlobalActivePower3 <- as.numeric(submydata$Global_active_power)
subMetering1 <- as.numeric(submydata$Sub_metering_1)
subMetering2 <- as.numeric(submydata$Sub_metering_2)
subMetering3 <- as.numeric(submydata$Sub_metering_3)
plot(date_time, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(date_time, subMetering2, type="l", col="red")
lines(date_time, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
png("plot3.png", width = 480, height = 480)
plot(date_time, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(date_time, subMetering2, type="l", col="red")
lines(date_time, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()

